-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bar_cocktails (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  recipe jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  bar_id uuid,
  name text,
  catalog_id uuid,
  is_private boolean DEFAULT false,
  submitted_by_bar_id text,
  base_spirit text,
  category text,
  method text,
  abv text,
  description_fr text,
  description_en text,
  profile jsonb,
  season jsonb,
  image text,
  tags jsonb,
  creation_year text,
  creator text,
  cocktail_style text,
  ice text,
  glass text,
  price numeric CHECK (price IS NULL OR price >= 0::numeric),
  CONSTRAINT bar_cocktails_pkey PRIMARY KEY (id),
  CONSTRAINT bar_cocktails_catalog_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES public.cocktails_catalog(id),
  CONSTRAINT cocktails_bar_id_fkey FOREIGN KEY (bar_id) REFERENCES public.bars(id)
);
CREATE TABLE public.ingredients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  type text NOT NULL,
  category text NOT NULL,
  available boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  abv real,
  family text,
  bar_id uuid,
  pricing_mode text NOT NULL DEFAULT 'bottle'::text CHECK (pricing_mode = ANY (ARRAY['bottle'::text, 'ml'::text])),
  bottle_price numeric CHECK (bottle_price IS NULL OR bottle_price >= 0::numeric),
  bottle_volume_ml numeric NOT NULL DEFAULT 700 CHECK (bottle_volume_ml > 0::numeric),
  price_per_ml numeric CHECK (price_per_ml IS NULL OR price_per_ml >= 0::numeric),
  references jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT ingredients_pkey PRIMARY KEY (id),
  CONSTRAINT ingredients_bar_id_fkey FOREIGN KEY (bar_id) REFERENCES public.bars(id)
);
CREATE TABLE public.menu_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  cocktail_ids ARRAY DEFAULT '{}'::uuid[],
  created_at timestamp with time zone DEFAULT now(),
  bar_id uuid,
  is_visible boolean DEFAULT true,
  CONSTRAINT menu_cards_pkey PRIMARY KEY (id),
  CONSTRAINT menu_cards_bar_id_fkey FOREIGN KEY (bar_id) REFERENCES public.bars(id)
);
CREATE TABLE public.bars (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  owner_id uuid NOT NULL,
  invite_code text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  is_public boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  features jsonb NOT NULL DEFAULT '{"order": true, "share": true}'::jsonb,
  statistics jsonb,
  CONSTRAINT bars_pkey PRIMARY KEY (id),
  CONSTRAINT bars_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.drinker_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bar_id uuid NOT NULL,
  pseudo text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  token uuid DEFAULT gen_random_uuid() UNIQUE,
  CONSTRAINT drinker_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT drinker_profiles_bar_id_fkey FOREIGN KEY (bar_id) REFERENCES public.bars(id)
);
CREATE TABLE public.drinker_favorites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  drinker_id uuid NOT NULL,
  cocktail_id uuid NOT NULL,
  bar_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT drinker_favorites_pkey PRIMARY KEY (id),
  CONSTRAINT drinker_favorites_cocktail_id_fkey FOREIGN KEY (cocktail_id) REFERENCES public.bar_cocktails(id),
  CONSTRAINT drinker_favorites_bar_id_fkey FOREIGN KEY (bar_id) REFERENCES public.bars(id),
  CONSTRAINT drinker_favorites_drinker_id_fkey FOREIGN KEY (drinker_id) REFERENCES public.drinker_profiles(id)
);
CREATE TABLE public.drink_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  drinker_id uuid NOT NULL,
  cocktail_id uuid NOT NULL,
  bar_id uuid NOT NULL,
  ordered_at timestamp with time zone DEFAULT now(),
  CONSTRAINT drink_history_pkey PRIMARY KEY (id),
  CONSTRAINT drink_history_drinker_id_fkey FOREIGN KEY (drinker_id) REFERENCES public.drinker_profiles(id),
  CONSTRAINT drink_history_cocktail_id_fkey FOREIGN KEY (cocktail_id) REFERENCES public.bar_cocktails(id),
  CONSTRAINT drink_history_bar_id_fkey FOREIGN KEY (bar_id) REFERENCES public.bars(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bar_id uuid NOT NULL,
  drinker_id uuid NOT NULL,
  cocktail_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_bar_id_fkey FOREIGN KEY (bar_id) REFERENCES public.bars(id),
  CONSTRAINT orders_drinker_id_fkey FOREIGN KEY (drinker_id) REFERENCES public.drinker_profiles(id),
  CONSTRAINT orders_cocktail_id_fkey FOREIGN KEY (cocktail_id) REFERENCES public.bar_cocktails(id)
);
CREATE TABLE public.z_backup_cocktails_04_08_2026 (
  id uuid NOT NULL,
  name text,
  base_spirit text,
  category text,
  glass text,
  method text,
  difficulty text,
  abv text,
  description_fr text,
  profile jsonb,
  season jsonb,
  image text,
  tags jsonb,
  recipe jsonb,
  created_at timestamp with time zone,
  bar_id text,
  cocktail_style text,
  submitted_by_bar_id text,
  ice text,
  description_en text,
  creation_year text,
  creator text,
  CONSTRAINT z_backup_cocktails_04_08_2026_pkey PRIMARY KEY (id)
);
CREATE TABLE public.z_BACKUP_cocktails_pre_migration (
  id uuid NOT NULL,
  name text,
  base_spirit text,
  category text,
  glass text,
  method text,
  difficulty text,
  abv text,
  description_fr text,
  profile jsonb,
  season jsonb,
  image text,
  tags jsonb,
  recipe jsonb,
  created_at timestamp with time zone,
  bar_id text,
  cocktail_style text,
  submitted_by_bar_id text,
  ice text,
  description_en text,
  creation_year text,
  creator text,
  CONSTRAINT z_BACKUP_cocktails_pre_migration_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cocktails_catalog (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text,
  base_spirit text,
  category text,
  glass text,
  method text,
  abv text,
  description_fr text,
  profile jsonb,
  season jsonb,
  image text,
  tags jsonb,
  recipe jsonb,
  created_at timestamp with time zone,
  cocktail_style text,
  ice text,
  description_en text,
  creation_year text,
  creator text,
  submitted_by_bar_id uuid,
  price numeric,
  CONSTRAINT cocktails_catalog_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cocktail_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bar_id uuid NOT NULL,
  cocktail_id uuid NOT NULL,
  name text,
  servings integer NOT NULL CHECK (servings > 0),
  dilution_percent numeric NOT NULL DEFAULT 20 CHECK (dilution_percent >= 0::numeric),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cocktail_batches_pkey PRIMARY KEY (id),
  CONSTRAINT cocktail_batches_bar_id_fkey FOREIGN KEY (bar_id) REFERENCES public.bars(id),
  CONSTRAINT cocktail_batches_cocktail_id_fkey FOREIGN KEY (cocktail_id) REFERENCES public.bar_cocktails(id)
);
CREATE TABLE public.backup_ingredients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  type text NOT NULL,
  category text NOT NULL,
  available boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  abv real,
  family text,
  bar_id uuid,
  pricing_mode text NOT NULL DEFAULT 'bottle'::text CHECK (pricing_mode = ANY (ARRAY['bottle'::text, 'ml'::text])),
  bottle_price numeric CHECK (bottle_price IS NULL OR bottle_price >= 0::numeric),
  bottle_volume_ml numeric NOT NULL DEFAULT 700 CHECK (bottle_volume_ml > 0::numeric),
  price_per_ml numeric CHECK (price_per_ml IS NULL OR price_per_ml >= 0::numeric),
  CONSTRAINT backup_ingredients_pkey PRIMARY KEY (id),
  CONSTRAINT backup_ingredients_bar_id_fkey FOREIGN KEY (bar_id) REFERENCES public.bars(id)
);