create table public.cocktails_catalog (
  id uuid not null default extensions.uuid_generate_v4 (),
  name text null,
  base_spirit text null,
  category text null,
  glass text null,
  method text null,
  abv text null,
  description_fr text null,
  profile jsonb null,
  season jsonb null,
  image text null,
  tags jsonb null,
  recipe jsonb null,
  created_at timestamp with time zone null,
  cocktail_style text null,
  ice text null,
  description_en text null,
  creation_year text null,
  creator text null,
  submitted_by_bar_id uuid null,
  price numeric null,
  constraint cocktails_catalog_DEBUG_pkey primary key (id)
) TABLESPACE pg_default;