export const TYPE_LABELS = {
  fr: {
    bourbon:             "Bourbon",
    rye:                 "Rye Whiskey",
    scotch:              "Scotch Whisky",
    irish_whiskey:       "Irish Whiskey",
    peated_whisky:       "Islay Scotch",
    whiskey:             "Whiskey",
    rum:                 "Rhum",
    rum_agricol:         "Rhum Agricole",
    rum_cuban:           "Rhum Cubain",
    rum_jamaican:        "Rhum Jamaicain",
    rum_overproof:       "Rhum Overproof",
    cachaca:             "Cachaça",
    tequila:             "Tequila",
    tequila_reposado:    "Tequila Reposado",
    mezcal:              "Mezcal",
    gin:                 "Gin",
    gin_dry:             "Dry Gin",
    gin_navy:            "Navy Strength Gin",
    genever:             "Genièvre",
    vodka:               "Vodka",
    cognac:              "Cognac",
    brandy:              "Brandy",
    calvados:            "Calvados",
    pisco:               "Pisco",
    grappa:              "Grappa",
    absinthe:            "Absinthe",
    aquavit:             "Aquavit",
    pastis:              "Pastis",
    aperol:              "Aperol",
    campari:             "Campari",
    cynar:               "Cynar",
    fernet_branca:       "Fernet Branca",
    amaro:               "Amaro",
    suze:                "Suze",
    malort:              "Malört",
    chartreuse_green:    "Chartreuse Verte",
    chartreuse_yellow:   "Chartreuse Jaune",
    benedictine:         "Bénédictine",
    galliano:            "Galliano",
    allspice:            "AllSpice Dram",
    falernum:            "Falernum",
    swedish_punsch:      "Swedish Punsch",
    mint_licor:          "Liqueur Menthe",
    sambuca:             "Sambuca",
    triple_sec:          "Triple Sec",
    curacao:             "Curaçao",
    limoncello:          "Limoncello",
    italicus:            "Italicus",
    cherry_heering:      "Cherry Heering",
    maraschino:          "Maraschino",
    cassis_licor:        "Liqueur Cassis",
    mure_licor:          "Liqueur Mûre",
    sloe_gin:            "Sloe Gin",
    elderflower_licor:   "Liqueur de Sureau",
    violet_licor:        "Liqueur de Violette",
    apricot_licor:       "Liqueur Abricot",
    banana_licor:        "Liqueur Banane",
    mango_licor:         "Liqueur Mangue",
    peach_licor:         "Liqueur Pêche",
    midori:              "Midori",
    pimms:               "Pimm's",
    pear_licor:          "Liqueur de Poire",
    amaretto:            "Amaretto",
    frangelico:          "Frangelico",
    walnut_licor:        "Liqueur Noix",
    pit_licor:           "Liqueur de Noyaux",
    coffee_licor:        "Liqueur de Café",
    baileys:             "Baileys",
    licor_43:            "Liqueur 43",
    chocolate_licor:     "Liqueur Chocolat",
    drambuie:            "Drambuie",
    dry_vermouth:        "Vermouth Dry",
    blanc_vermouth:      "Vermouth Blanc",
    sweet_vermouth:      "Vermouth Sweet",
    lillet:              "Lillet",
    cocchi_americano:    "Cocchi Americano",
    sherry:              "Xérès / Sherry",
    porto:               "Porto",
    sparkling_wine:      "Vin Pétillant",
    sake:                "Saké",
    beer:                "Bière",
    ipa_beer:            "Bière IPA",
    stout_beer:          "Stout",
    red_wine:            "Vin Rouge",
    dry_white_wine:      "Vin Blanc Sec",
    sweet_white_wine:    "Vin Blanc Doux",
    rose_wine:           "Vin Rosé",
    lemon_juice:          "Jus de citron",
    lime_juice:           "Jus de Lime",
    orange_juice:         "Jus d'orange",
    grapefruit_juice:     "Jus de pamplemousse",
    pineapple_juice:      "Jus d'ananas",
    cranberry_juice:      "Jus de cranberry",
    apple_juice:          "Jus de pomme",
    passion_juice:        "Jus de passion",
    tomato_juice:         "Jus de tomate",
    simple_syrup:         "Sirop simple",
    semi_simple_syrup:    "Sirop semi",
    rich_simple_syrup:    "Sirop riche",
    honey_syrup:          "Sirop de miel",
    grenadine:            "Grenadine",
    orgeat:               "Orgeat",
    agave_syrup:          "Sirop d'agave",
    cinnamon_syrup:       "Sirop de cannelle",
    passion_fruit_syrup:  "Sirop de passion",
    raspberry_syrup:      "Sirop de framboise",
    vanilla_syrup:        "Sirop de vanille",
    maple_syrup:          "Sirop d'érable",
    demerara_syrup:       "Sirop Demerara",
    coconut_syrup:        "Sirop de coco",
    guava_syrup:          "Sirop de Goyave",
    ginger_syrup:         "Sirop de Gingembre",
    hibiscus_syrup:       "Sirop d'Hibiscus",
    redcurrant_syrup:     "Sirop de Groseille",
    angostura_bitters:    "Angostura Bitters",
    peychaud_bitters:     "Peychaud's Bitters",
    orange_bitters:       "Orange Bitters",
    chocolate_bitters:    "Chocolate Bitters",
    celery_bitters:       "Celery Bitters",
    walnut_bitters:       "Walnut Bitters",
    bitters:              "Bitters",
    club_soda:            "Eau gazeuse",
    tonic_water:          "Tonic",
    ginger_soda:          "Ginger Beer",
    cola:                 "Cola",
    coconut_cream:        "Crème de coco",
    lemon_zest:           "Zeste Citron",
    lime_zest:            "Zeste Lime",
    orange_zest:          "Zeste Orange",
    grapefruit_zest:      "Zeste Pamplemousse",
    lemon_swath:          "Swath Citron",
    lime_swath:           "Swath Lime",
    orange_swath:         "Swath Orange",
    grapefruit_swath:     "Swath Pamplemousse",
    lime_wheel:           "Rondelle Lime",
    lemon_wheel:          "Rondelle Citron",
    orange_wheel:         "Rondelle Orange",
    pineapple:            "Ananas",
    pineapple_fronds:     "Feuilles Ananas",
    cocktail_cherry:      "Cerise",
    olive:                "Olive",
    nutmeg:               "Muscade",
    mint:                 "Menthe",
    cucumber:             "Concombre",
    strawberry:           "Fraise",
    celery:               "Céleri",
    salt:                 "Sel",
    sugar_rim:            "Sucre (bord)",
    dried_fruit:          "Fruits séchés",
    cinnamon_stick:       "Bâton de cannelle",
    grape:                "Raisin",
    aquafaba:             "Aquafaba",
    egg:                  "Œuf entier",
    heavy_cream:          "Crème épaisse",
    milk:                 "Lait",
    butter:               "Beurre",
    coffee:               "Café",
    cold_brew:            "Cold Brew",
    tea:                  "Thé",
    matcha:               "Matcha",
    hot_sauce:            "Sauce piquante",
    worcestershire:       "Worcestershire",
    water:                "Eau",
    hot_water:            "Eau chaude",
  },
  en: {
    bourbon:             "Bourbon",
    rye:                 "Rye Whiskey",
    scotch:              "Scotch Whisky",
    irish_whiskey:       "Irish Whiskey",
    peated_whisky:       "Islay Scotch",
    whiskey:             "Whiskey",
    rum:                 "Rum",
    rum_agricol:         "Rhum Agricole",
    rum_cuban:           "Cuban Rum",
    rum_jamaican:        "Jamaican Rum",
    rum_overproof:       "Overproof Rum",
    cachaca:             "Cachaça",
    tequila:             "Tequila",
    tequila_reposado:    "Tequila Reposado",
    mezcal:              "Mezcal",
    gin:                 "Gin",
    gin_dry:             "Dry Gin",
    gin_navy:            "Navy Strength Gin",
    genever:             "Genever",
    vodka:               "Vodka",
    cognac:              "Cognac",
    brandy:              "Brandy",
    calvados:            "Calvados",
    pisco:               "Pisco",
    grappa:              "Grappa",
    absinthe:            "Absinthe",
    aquavit:             "Aquavit",
    pastis:              "Pastis",
    aperol:              "Aperol",
    campari:             "Campari",
    cynar:               "Cynar",
    fernet_branca:       "Fernet Branca",
    amaro:               "Amaro",
    suze:                "Suze",
    malort:              "Malört",
    chartreuse_green:    "Green Chartreuse",
    chartreuse_yellow:   "Yellow Chartreuse",
    benedictine:         "Bénédictine",
    galliano:            "Galliano",
    allspice:            "AllSpice Dram",
    falernum:            "Falernum",
    swedish_punsch:      "Swedish Punsch",
    mint_licor:          "Mint Liqueur",
    sambuca:             "Sambuca",
    triple_sec:          "Triple Sec",
    curacao:             "Curaçao",
    limoncello:          "Limoncello",
    italicus:            "Italicus",
    cherry_heering:      "Cherry Heering",
    maraschino:          "Maraschino",
    cassis_licor:        "Blackcurrant Liqueur",
    mure_licor:          "Blackberry Liqueur",
    sloe_gin:            "Sloe Gin",
    elderflower_licor:   "Elderflower Liqueur",
    violet_licor:        "Violet Liqueur",
    apricot_licor:       "Apricot Liqueur",
    banana_licor:        "Banana Liqueur",
    mango_licor:         "Mango Liqueur",
    peach_licor:         "Peach Liqueur",
    midori:              "Midori",
    pimms:               "Pimm's",
    pear_licor:          "Pear Liqueur",
    amaretto:            "Amaretto",
    frangelico:          "Frangelico",
    walnut_licor:        "Walnut Liqueur",
    pit_licor:           "Stone Fruit Liqueur",
    coffee_licor:        "Coffee Liqueur",
    baileys:             "Baileys",
    licor_43:            "Licor 43",
    chocolate_licor:     "Chocolate Liqueur",
    drambuie:            "Drambuie",
    dry_vermouth:        "Dry Vermouth",
    blanc_vermouth:      "Blanc Vermouth",
    sweet_vermouth:      "Sweet Vermouth",
    lillet:              "Lillet",
    cocchi_americano:    "Cocchi Americano",
    sherry:              "Sherry",
    porto:               "Port",
    sparkling_wine:      "Sparkling Wine",
    sake:                "Sake",
    beer:                "Beer",
    ipa_beer:            "IPA Beer",
    stout_beer:          "Stout",
    red_wine:            "Red Wine",
    dry_white_wine:      "Dry White Wine",
    sweet_white_wine:    "Sweet White Wine",
    rose_wine:           "Rosé Wine",
    lemon_juice:          "Lemon Juice",
    lime_juice:           "Lime Juice",
    orange_juice:         "Orange Juice",
    grapefruit_juice:     "Grapefruit Juice",
    pineapple_juice:      "Pineapple Juice",
    cranberry_juice:      "Cranberry Juice",
    apple_juice:          "Apple Juice",
    passion_juice:        "Passion Fruit Juice",
    tomato_juice:         "Tomato Juice",
    simple_syrup:         "Simple Syrup",
    semi_simple_syrup:    "Medium Syrup",
    rich_simple_syrup:    "Rich Syrup",
    honey_syrup:          "Honey Syrup",
    grenadine:            "Grenadine",
    orgeat:               "Orgeat",
    agave_syrup:          "Agave Syrup",
    cinnamon_syrup:       "Cinnamon Syrup",
    passion_fruit_syrup:  "Passion Fruit Syrup",
    raspberry_syrup:      "Raspberry Syrup",
    vanilla_syrup:        "Vanilla Syrup",
    maple_syrup:          "Maple Syrup",
    demerara_syrup:       "Demerara Syrup",
    coconut_syrup:        "Coconut Syrup",
    guava_syrup:          "Guava Syrup",
    ginger_syrup:         "Ginger Syrup",
    hibiscus_syrup:       "Hibiscus Syrup",
    redcurrant_syrup:     "Redcurrant Syrup",
    angostura_bitters:    "Angostura Bitters",
    peychaud_bitters:     "Peychaud's Bitters",
    orange_bitters:       "Orange Bitters",
    chocolate_bitters:    "Chocolate Bitters",
    celery_bitters:       "Celery Bitters",
    walnut_bitters:       "Walnut Bitters",
    bitters:              "Bitters",
    club_soda:            "Club Soda",
    tonic_water:          "Tonic Water",
    ginger_soda:          "Ginger Beer",
    cola:                 "Cola",
    coconut_cream:        "Coconut Cream",
    lemon_zest:           "Lemon Zest",
    lime_zest:            "Lime Zest",
    orange_zest:          "Orange Zest",
    grapefruit_zest:      "Grapefruit Zest",
    lemon_swath:          "Lemon Twist",
    lime_swath:           "Lime Twist",
    orange_swath:         "Orange Twist",
    grapefruit_swath:     "Grapefruit Twist",
    lime_wheel:           "Lime Wheel",
    lemon_wheel:          "Lemon Wheel",
    orange_wheel:         "Orange Wheel",
    pineapple:            "Pineapple",
    pineapple_fronds:     "Pineapple Fronds",
    cocktail_cherry:      "Cocktail Cherry",
    olive:                "Olive",
    nutmeg:               "Nutmeg",
    mint:                 "Mint",
    cucumber:             "Cucumber",
    strawberry:           "Strawberry",
    celery:               "Celery",
    salt:                 "Salt",
    sugar_rim:            "Sugar Rim",
    dried_fruit:          "Dried Fruit",
    cinnamon_stick:       "Cinnamon Stick",
    grape:                "Grape",
    aquafaba:             "Aquafaba",
    egg:                  "Whole Egg",
    heavy_cream:          "Heavy Cream",
    milk:                 "Milk",
    butter:               "Butter",
    coffee:               "Coffee",
    cold_brew:            "Cold Brew",
    tea:                  "Tea",
    matcha:               "Matcha",
    hot_sauce:            "Hot Sauce",
    worcestershire:       "Worcestershire",
    water:                "Water",
    hot_water:            "Hot Water",
  },
}

export function getTypeLabel(type, locale = 'fr') {
  return TYPE_LABELS[locale]?.[type] ?? type
}

export const FAMILY_LABELS = {
  fr: {
    // Familles spiritueux
    'Whiskey':        '🥃 Whiskey',
    'Rum':            '🍹 Rhum',
    'Agave':          '🌵 Agave',
    'Gin':            '🌿 Gin',
    'Brandy':         '🍇 Brandy',
    'Vodka':          '❄️ Vodka',
    'Absinthe':       '🌱 Absinthe',
    'Aquavit':        '🌾 Aquavit',
    // Sous-types
    'bourbon':        '🌽 Bourbon',
    'rye':            '🌾 Rye',
    'scotch':         '🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotch',
    'irish_whiskey':  '☘️ Irish',
    'peated_whisky':  '🔥 Peated/Islay',
    'whiskey':        '🥃 Autre Whiskey',
    'rum':            '🍹 Rhum blanc',
    'rum_agricol':    '🌿 Rhum Agricole',
    'rum_jamaican':   '🇯🇲 Jamaïcain',
    'rum_cuban':      '🇨🇺 Cubain',
    'rum_overproof':  '💥 Overproof',
    'cachaca':        '🇧🇷 Cachaça',
    'tequila':        '🌵 Tequila Blanco',
    'tequila_reposado':'🪵 Tequila Reposado',
    'mezcal':         '🔥 Mezcal',
    'gin':            '🌿 Gin',
    'gin_dry':        '🍋 Dry Gin',
    'gin_navy':       '⚓ Navy Strength',
    'genever':        '🇳🇱 Genièvre',
    'cognac':         '🇫🇷 Cognac',
    'calvados':       '🍎 Calvados',
    'pisco':          '🇵🇪 Pisco',
    'grappa':         '🍇 Grappa',
    'brandy':         '🍇 Brandy',
    // Liqueurs
    'Liqueur Amer':    '🍊 Amer',
    'Liqueur Agrume':  '🍋 Agrume',
    'Liqueur Fruits':  '🍒 Fruits',
    'Liqueur Herbes':  '🌿 Herbes',
    'Liqueur Noix':    '🌰 Noix',
    'Liqueur Dessert': '☕ Dessert',
    'Liqueur Anisée':  '⭐ Anisée',
    // Saisons
    'all':    '🍸 Toutes',
    'spring': '🌸 Printemps',
    'summer': '☀️ Été',
    'fall':   '🍂 Automne',
    'winter': '❄️ Hiver',
  },
  en: {
    // Familles spiritueux
    'Whiskey':        '🥃 Whiskey',
    'Rum':            '🍹 Rum',
    'Agave':          '🌵 Agave',
    'Gin':            '🌿 Gin',
    'Brandy':         '🍇 Brandy',
    'Vodka':          '❄️ Vodka',
    'Absinthe':       '🌱 Absinthe',
    'Aquavit':        '🌾 Aquavit',
    // Sous-types
    'bourbon':        '🌽 Bourbon',
    'rye':            '🌾 Rye',
    'scotch':         '🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotch',
    'irish_whiskey':  '☘️ Irish',
    'peated_whisky':  '🔥 Peated/Islay',
    'whiskey':        '🥃 Other Whiskey',
    'rum':            '🍹 White Rum',
    'rum_agricol':    '🌿 Rhum Agricole',
    'rum_jamaican':   '🇯🇲 Jamaican',
    'rum_cuban':      '🇨🇺 Cuban',
    'rum_overproof':  '💥 Overproof',
    'cachaca':        '🇧🇷 Cachaça',
    'tequila':        '🌵 Tequila Blanco',
    'tequila_reposado':'🪵 Tequila Reposado',
    'mezcal':         '🔥 Mezcal',
    'gin':            '🌿 Gin',
    'gin_dry':        '🍋 Dry Gin',
    'gin_navy':       '⚓ Navy Strength',
    'genever':        '🇳🇱 Genever',
    'cognac':         '🇫🇷 Cognac',
    'calvados':       '🍎 Calvados',
    'pisco':          '🇵🇪 Pisco',
    'grappa':         '🍇 Grappa',
    'brandy':         '🍇 Brandy',
    // Liqueurs
    'Liqueur Amer':    '🍊 Bitter',
    'Liqueur Agrume':  '🍋 Citrus',
    'Liqueur Fruits':  '🍒 Fruit',
    'Liqueur Herbes':  '🌿 Herbal',
    'Liqueur Noix':    '🌰 Nut',
    'Liqueur Dessert': '☕ Dessert',
    'Liqueur Anisée':  '⭐ Anise',
    // Saisons
    'all':    '🍸 All',
    'spring': '🌸 Spring',
    'summer': '☀️ Summer',
    'fall':   '🍂 Fall',
    'winter': '❄️ Winter',
  },
}

export function getFamilyLabel(key, locale = 'fr') {
  return FAMILY_LABELS[locale]?.[key] ?? key
}

export const PROFILE_LABELS = {
  fr: {
    Smoky:      'Fumé',
    Bitter:     'Amer',
    Creamy:     'Crémeux',
    Tropical:   'Tropical',
    Floral:     'Floral',
    Nutty:      'Noisetté',
    Spicy:      'Épicé',
    Herbal:     'Herbacé',
    Fruity:     'Fruité',
    Citrus:     'Agrume',
    Sour:       'Acidulé',
    Dry:        'Sec',
    Boozy:      'Corsé',
    Refreshing: 'Frais',
    Rich:       'Riche',
    Sweet:      'Sucré',
  },
  en: {
    Smoky:      'Smoky',
    Bitter:     'Bitter',
    Creamy:     'Creamy',
    Tropical:   'Tropical',
    Floral:     'Floral',
    Nutty:      'Nutty',
    Spicy:      'Spicy',
    Herbal:     'Herbal',
    Fruity:     'Fruity',
    Citrus:     'Citrus',
    Sour:       'Sour',
    Dry:        'Dry',
    Boozy:      'Boozy',
    Refreshing: 'Refreshing',
    Rich:       'Rich',
    Sweet:      'Sweet',
  },
}

export function getProfileLabel(profile, locale = 'fr') {
  return PROFILE_LABELS[locale]?.[profile] ?? profile
}