"""
Table de référence des ABV (% alcool par volume)
"""

INGREDIENT_ABV = {
    # Base spirits
    'absinthe':          65.0,
    'aquavit':           40.0,
    'bourbon':           40.0,
    'brandy':            40.0,
    'cachaca':           40.0,
    'calvados':          40.0,
    'cognac':            40.0,
    'genever':           35.0,
    'gin':               40.0,
    'gin_dry':           40.0,
    'gin_navy':          57.0,
    'grappa':            42.0,
    'irish_whiskey':     40.0,
    'mezcal':            42.0,
    'peated_whisky':     43.0,
    'pisco':             40.0,
    'rum':               40.0,
    'rum_agricol':       50.0,
    'rum_cuban':         40.0,
    'rum_jamaican':      40.0,
    'rum_overproof':     63.0,
    'rye':               40.0,
    'scotch':            40.0,
    'tequila':           40.0,
    'tequila_reposado':  40.0,
    'vodka':             40.0,
    'whiskey':           40.0,
    
    # Liqueurs
    'allspice':          22.0,
    'amaretto':          21.0,
    'amaro':             30.0,
    'aperol':            11.0,
    'apricot_licor':     25.0,
    'baileys':           17.0,
    'banana_licor':      20.0,
    'benedictine':       40.0,
    'campari':           24.0,
    'cassis_licor':      16.0,
    'chartreuse_green':  55.0,
    'chartreuse_yellow': 40.0,
    'cherry_heering':    24.0,
    'chocolate_licor':   20.0,
    'coffee_licor':      20.0,
    'curacao':           40.0,
    'cynar':             16.5,
    'drambuie':          40.0,
    'elderflower_licor': 20.0,
    'falernum':          11.0,
    'fernet_branca':     39.0,
    'frangelico':        20.0,
    'galliano':          42.3,
    'licor_43':          31.0,
    'limoncello':        26.0,
    'maraschino':        32.0,
    'midori':            20.0,
    'mint_licor':        25.0,
    'mure_licor':        18.0,
    'sambuca':           38.0,
    'suze':              20.0,
    'triple_sec':        40.0,
    
    # Fortified wines / modifiers
    'beer':              5.0,
    'blanc_vermouth':    18.0,
    'dry_vermouth':      18.0,
    'lillet':            17.0,
    'porto':             20.0,
    'red_wine':          13.0,
    'rose_wine':         12.0,
    'sake':              15.0,
    'sherry':            17.0,
    'sparkling_wine':    12.0,
    'sweet_vermouth':    16.0,
    
    # Bitters
    'angostura_bitters': 44.7,
    'bitters':           40.0,
    'celery_bitters':    40.0,
    'chocolate_bitters': 40.0,
    'orange_bitters':    28.0,
    'peychaud_bitters':  35.0,
    'walnut_bitters':    40.0,
}